site_name: Design de Software - Insper 2020/2
site_author: Andrew Kurauchi, Lucianos Soares

extra:
    materia: Design de Software
    professor: Andrew Kurauchi, Luciano Soares
    semestre: 2020/2

theme:
  feature:
    tabs: true
  name: 'material'
  palette:
      primary: 'indigo'
      accent: 'blue'
  font:
    text: Roboto
    code: Roboto Mono
  custom_dir: 'custom_theme'

docs_dir: material
site_dir: docs

site_url: https://insper.github.io/design-de-software/


nav:
    - Home: index.md
    - Turmas:
        - 'Turma A': turma-a.md
        - 'Turma B': turma-b.md
    - 'Servidor de Exercícios': http://softdes.insper.edu.br/
    - Aulas:
        - '01 - Introdução ao Python, Variáveis, Operações Matemáticas e Funções':
            - 'Handout': aulas/01-funcoes.md
            - 'Slides': aulas/01-funcoes/01-slides.pdf
            - 'Vídeo': https://www.youtube.com/watch?v=VtNiBiJ60yo
        - '02 - Input e String':
            - 'Handout': aulas/02-io.md
            - 'Slides': aulas/02-io/02-slides.pdf
            - 'Vídeo': https://youtu.be/vNhvNjJ32oc
        - '03 - Desvios Condicionais (if)':
            - 'Handout': aulas/03-if.md
            - 'Slides': aulas/03-if/03-slides.pdf
            - 'Vídeo': https://www.youtube.com/watch?v=rI40ujoXpeQ
        - '04 - Laços de Repetição (while)':
            - 'Handout': aulas/04-while.md
            - 'Vídeo': https://www.youtube.com/watch?v=rHOkYSMjj18
        - '05 - Listas':
            - 'Handout': aulas/05-listas.md
            - 'Vídeo': https://www.youtube.com/watch?v=ZA_cfIZW1pA
        - '06 - For':
            - 'Handout': aulas/06-for.md
            - 'Vídeo': https://www.youtube.com/watch?v=UC5TY403DrE
        - '07 - Dicionários':
            - 'Handout': aulas/07-dicionarios.md
            - 'Vídeo': https://www.youtube.com/watch?v=lSDhCUIPg38
        - '08 - Strings e Fatiamento':
            - 'Handout': aulas/08-strings.md
            - 'Vídeo': https://www.youtube.com/watch?v=jkH1ICesA9A
        - '09 - Arquivos':
            - 'Handout': aulas/09-arquivos.md
            - 'Vídeo': https://www.youtube.com/watch?v=evKHVN8gcz8
    - Projeto:
        - 'Handout': aulas/10-pygame.md
        - 'Vídeos':
            - 'Classes': https://www.youtube.com/watch?v=27xvt8_WTug
            - 'Exemplo PyGame 1': https://www.youtube.com/watch?v=bH-Js1Eao50
            - 'Exemplo PyGame 2': https://www.youtube.com/watch?v=5R5WN1oRmvg
            - 'Exemplo PyGame 3': https://www.youtube.com/watch?v=bzal5efE6XQ
            - 'Exemplo PyGame 4': https://www.youtube.com/watch?v=h-H6NdRzCTY
            - 'Exemplo PyGame 5': https://www.youtube.com/watch?v=HTNmmUA3bOU
            - 'Exemplo PyGame 6': https://www.youtube.com/watch?v=H7jZK08NFlY
            - 'Exemplo PyGame 7': https://www.youtube.com/watch?v=TSZ6d1eN6Do
            - 'Exemplo PyGame 8': https://www.youtube.com/watch?v=rxgEYY-IwZc
            - 'Exemplo PyGame 9': https://www.youtube.com/watch?v=jZmCRmAQlzE
            - 'Exemplo PyGame 10': https://www.youtube.com/watch?v=sdurCruVfsQ
            - 'git e Github': https://www.youtube.com/watch?v=xZI0BytK5GA
    - Tutoriais:
        - 'Navegando pelo terminal':
            - 'Windows': tutoriais/terminal-win.md
            - 'macOS': tutoriais/terminal-macos.md
    - Dicas:
        - 'Buscando Ajuda': dicas/buscando-ajuda.md

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS_HTML
    - translate-admonitions.js

extra_css:
    - css/printing.css
    - css/dessoft.css

markdown_extensions:
  - markdown.extensions.tables
  - tables
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.attr_list
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets:
      base_path: material/aulas
      check_paths: true
plugins:
    - search
